### ISSUE TITLE
Cannot call open-input-string using a variable

### ISSUE THREAD

**Issue by dcecile** [justinethier/husk-scheme#199] opened 2015-01-21 04:24 UTC
Calling `open-input-string` using a variable (or a function parameter) results in a very odd error message:

    Expected 1 args; found values <ptr x>

(While technically a separate issue about error messages... first, it was hard to figure out that `open-input-string` was the culprit, second the "found values" didn't say it was only one value, third without knowing Husk internals "ptr" isn't clear.)

Here's how to trigger it:

```scheme
(define x "test")
(open-input-string x)

(define (y z) (open-input-string z))
(y "test")
```

**Comment by justinethier** [comment] 2015-01-21 18:56
Thanks for the bug report, and sorry about that. I added code to handle variables passed to `open-input-string` and other related I/O functions. And added you test code to the unit test suite :)

Part of the problem is the error message was misleading because it should have given you a type mismatch if one argument of the wrong type is passed. This has been fixed. Otherwise... I agree the error handling could be better to identify which function actually raises an error. Maybe by keeping the last `n` stack frames and printing them as well. There is an open ticket for this.

I agree `<ptr x>` is not that great. Do you think `<variable: x>` is any better? At least that tells you that a variable is involved.

All of these changes will be in a 3.18.1 release. You can grab them off of `master` in the meantime.

**Comment by dcecile** [comment] 2015-01-21 23:43
:) Thanks, the new changes off of `master` are all working fine for me.

Printing stack frames during errors would definitely be a boon, because without context, a legitimate type or argument number error could come from any piece of untested/buggy Scheme code.

About `<ptr x>` vs. `<variable: x>`... It's a bit confusing because I thought that Scheme was always pass-by-value. Also, whether or not the `<ptr x>` gets shown in the error message depends on the type of the variable's object (e.g. numbers don't get passed by pointer).

Exposing this implementation detail through an error message seems unnecessary when other errors (like type errors) will show the value at the pointer.

For argument number mismatches, what do you think about always unboxing pointers to print variable values, and print the number "found X values" as well?

**Comment by justinethier** [comment] 2015-01-22 02:58
No problem. 

[Issue #1] (https://github.com/justinethier/husk-scheme/issues/1) deals with the call history - not a trivial change but it would be huge for debugging.

Adding "found X values" to the NumArgs error is a good idea, I'll add that.

The fact a pointer is there is an implementation detail that should, ideally, never be exposed to the user. What needs to happen is any functions that execute within the I/O monad need to unbox pointers before throwing a `LispError` that includes any passed objects. Unfortunately that is being done inconsistently right now, so `<ptr>` types can slip through.

**Comment by justinethier** [comment] 2015-01-22 04:06
This patch to `showLispError` should be sufficient to prevent errors from containing raw `<ptr>` types.

**Comment by dcecile** [comment] 2015-01-22 11:51
Yup, the patch works for me, so feel free to close this issue :)

**Comment by justinethier** [comment] 2015-01-22 14:44
Done - thanks again!

**Closed by justinethier** 2015-01-22 14:44 UTC
